Repository HTTPArchive/data-pipeline, pull requests merged in 2022-05, with the labels that each got.

#54 Fix unpacking TypeError #50
  modules/transformation.py
Labels: bug

#56 Update run_pipeline* shell scripts and README.md
  README.md
  run_pipeline_batch.sh
  run_pipeline_streaming.sh
Labels: documentation

#55 Implement BigQuery deadletter logging
  modules/import_har.py
Labels: enhancement

#57 Feat/update streaming pipeline
  README.md
  run_pipeline_streaming.sh
Labels: enhancement

#61 Fix for issue #60; add lower-bound to clamping
  modules/transformation.py
  modules/utils.py
  test/test_transformation.py
  test/test_utils.py
Labels: bug, enhancement

#62 Add guards to reduce batch pipeline errors
  modules/transformation.py
  modules/utils.py
Labels: enhancement

#64 Batch pipeline improvements
  modules/import_har.py
  run_pipeline_batch.sh
Labels: enhancement

#69 Clamp all integer columns
  modules/transformation.py
  modules/utils.py
  test/test_utils.py
Labels: bug

#74 Ensure avg_dom_depth is an int
  modules/transformation.py
Labels: bug

#76 Handle None avg_dom_depth
  modules/transformation.py
Labels: bug

#78 Handle wss?://
  modules/transformation.py
Labels: enhancement

#80 Update reference to `json.JSONDecodeError`
  modules/transformation.py
Labels: enhancement
